In [1]:
import numpy as np

import statsmodels.api as sm

import statsmodels.formula.api as smf
import pandas as pd

C:\Users\QUYEN\Anaconda2\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [2]:
cd E:\HK6\Phân tích dữ liệu kinh doanh\BaiTap\BaiTapLap04

E:\HK6\Phân tích dữ liệu kinh doanh\BaiTap\BaiTapLap04

In [3]:
pd.read_csv('Colleges and Universities.csv')

,School,Type,Median SAT,Acceptance Rate,Expenditures/Student,Top 10% HS,Graduation %
0,Amherst,Lib Arts,1315.0,0.22,26636.0,85.0,93.0
1,Barnard,Lib Arts,1220.0,0.53,17653.0,69.0,80.0
2,Bates,Lib Arts,1240.0,0.36,17554.0,58.0,88.0
3,Berkeley,University,1176.0,0.37,23665.0,95.0,68.0
4,Bowdoin,Lib Arts,1300.0,0.24,25703.0,78.0,90.0
5,Brown,University,1281.0,0.24,24201.0,80.0,90.0
6,Bryn Mawr,Lib Arts,1255.0,0.56,18847.0,70.0,84.0
7,Cal Tech,University,1400.0,0.31,102262.0,98.0,75.0
8,Carleton,Lib Arts,1300.0,0.40,15904.0,75.0,80.0
9,Carnegie Mellon,University,1225.0,0.64,33607.0,52.0,77.0
10,Claremont McKenna,Lib Arts,1260.0,0.36,20377.0,68.0,74.0
11,Colby,Lib Arts,1200.0,0.46,18872.0,52.0,84.0
12,Colgate,Lib Arts,1258.0,0.38,17520.0,61.0,85.0
13,Columbia,University,1268.0,0.29,45879.0,78.0,90.0
14,Cornell,University,1280.0,0.30,37137.0,85.0,83.0
15,Davisdson,Lib Arts,1230.0,0.36,17721.0,77.0,89.0
16,Duke,University,1310.0,0.25,39504.0,91.0,91.0
17,Georgetown,University,1278.0,0.24,23115.0,79.0,89.0
18,Grinnell,Lib Arts,1244.0,0.67,22301.0,65.0,73.0
19,Hamilton,Lib Arts,1215.0,0.38,20722.0,51.0,85.0
20,Harvard,University,1370.0,0.18,46918.0,90.0,90.0
21,Haverford,Lib Arts,1285.0,0.35,19418.0,71.0,87.0
22,Johns Hopkins,University,1290.0,0.48,45460.0,69.0,86.0
23,Middlebury,Lib Arts,1255.0,0.25,24718.0,65.0,92.0
24,MIT,University,1357.0,0.30,56766.0,95.0,86.0
25,Mount Holyoke,Lib Arts,1200.0,0.61,23358.0,47.0,83.0
26,Northwestern,University,1230.0,0.47,28851.0,77.0,82.0
27,Oberlin,Lib Arts,1247.0,0.54,23591.0,64.0,77.0
28,Occidental,Lib Arts,1170.0,0.49,20192.0,54.0,72.0
29,Pomona,Lib Arts,1320.0,0.33,26668.0,79.0,80.0
30,Princeton,University,1340.0,0.17,48123.0,89.0,93.0
31,Rice,University,1327.0,0.24,26730.0,85.0,88.0
32,Smith,Lib Arts,1195.0,0.57,25271.0,65.0,87.0
33,Stanford,University,1370.0,0.18,61921.0,92.0,88.0
34,Swarthnore,Lib Arts,1310.0,0.24,27487.0,78.0,88.0
35,U Michigan,University,1195.0,0.60,21853.0,71.0,77.0
36,U of Chicago,University,1300.0,0.45,38937.0,74.0,73.0
37,U of Rochester,University,1155.0,0.56,38597.0,52.0,73.0
38,U Pennsylvania,University,1280.0,0.41,30882.0,87.0,86.0
39,U Va,University,1218.0,0.37,19365.0,77.0,88.0
40,UCLA,University,1142.0,0.43,26859.0,96.0,61.0
41,UNC,University,1109.0,0.32,19684.0,82.0,73.0
42,Vassar,Lib Arts,1287.0,0.43,20179.0,53.0,84.0
43,Washington U (MO),University,1225.0,0.54,39883.0,71.0,76.0
44,Washinton and Lee,Lib Arts,1234.0,0.29,17998.0,61.0,78.0
45,Wellesley,Lib Arts,1250.0,0.49,27879.0,76.0,86.0
46,Wesleyan (CT),Lib Arts,1290.0,0.35,19948.0,73.0,91.0
47,Williams,Lib Arts,1336.0,0.28,23772.0,86.0,93.0
48,Yale,University,1350.0,0.19,52468.0,90.0,93.0

In [4]:
x=pd.read_csv('Colleges and Universities.csv')
x.head()

,School,Type,Median SAT,Acceptance Rate,Expenditures/Student,Top 10% HS,Graduation %
0,Amherst,Lib Arts,1315.0,0.22,26636.0,85.0,93.0
1,Barnard,Lib Arts,1220.0,0.53,17653.0,69.0,80.0
2,Bates,Lib Arts,1240.0,0.36,17554.0,58.0,88.0
3,Berkeley,University,1176.0,0.37,23665.0,95.0,68.0
4,Bowdoin,Lib Arts,1300.0,0.24,25703.0,78.0,90.0

In [5]:
import statsmodels.api as sm # import statsmodels 
## Y usually means our output/dependent variable
y = x["Graduation %"] 
## X usually means our input variables (or independent variables)
X = x[["Median SAT","Acceptance Rate","Expenditures/Student","Top 10% HS"] ]
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model

# Note the difference in argument order
model = sm.OLS(y, X).fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           Graduation %   R-squared:                       0.534
Model:                            OLS   Adj. R-squared:                  0.492
Method:                 Least Squares   F-statistic:                     12.63
Date:                Sun, 20 May 2018   Prob (F-statistic):           6.33e-07
Time:                        00:01:38   Log-Likelihood:                -148.69
No. Observations:                  49   AIC:                             307.4
Df Residuals:                      44   BIC:                             316.8
Df Model:                           4
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                   17.9210     24.557      0.730      0.469     -31.571      67.413
Median SAT               0.0720      0.018      4.004      0.000       0.036       0.108
Acceptance Rate        -24.8592      8.315     -2.990      0.005     -41.617      -8.101
Expenditures/Student    -0.0001   6.59e-05     -2.057      0.046      -0.000   -2.77e-06
Top 10% HS              -0.1628      0.079     -2.051      0.046      -0.323      -0.003
==============================================================================
Omnibus:                        1.954   Durbin-Watson:                   2.010
Prob(Omnibus):                  0.376   Jarque-Bera (JB):                1.833
Skew:                          -0.450   Prob(JB):                        0.400
Kurtosis:                       2.706   Cond. No.                     1.12e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.12e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""